/**
 * Build the hashline web client bundle: bundles `src/client.ts` (self-contained,
 * no external requires — React/ctx/styles are client builtins) into the
 * `window.__ModuleLoader__.load({ id, factory })` framing `dsh-web` expects,
 * written to `lib/client.js`. The `__DSH_BOOT__` graph fetches this file at
 * `/plugins/<pkg-name>/client.js` and the package loader entry name (the npm
 * package name) is the module id the bundle must register under.
 */
import { build } from 'esbuild'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const PACKAGE_ID = 'dsh-tool-hashline'
const out = resolve(root, 'lib/client.js')

const result = await build({
  entryPoints: [resolve(root, 'src/client.ts')],
  bundle: true,
  format: 'cjs',
  platform: 'browser',
  target: 'es2020',
  write: false,
  logLevel: 'warning',
})

const bundle = result.outputFiles[0].text.replace(/\n$/, '')
const indent = (text) => text.split('\n').map((line) => `    ${line}`).join('\n')
const wrapped = `/* dsh-tool-hashline web client bundle — generated by scripts/build-client.mjs */
window.__ModuleLoader__.load({
  id: ${JSON.stringify(PACKAGE_ID)},
  factory: (require) => {
    "use strict";
    var module = { exports: {} };
    var exports = module.exports;
${indent(bundle)}
    return module.exports;
  }
});
`

mkdirSync(dirname(out), { recursive: true })
writeFileSync(out, wrapped)
console.log(`client: ${out} (${wrapped.length} bytes)`)
